services:

  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - ./ny_taxi_data:/var/lib/postgresql/data:rw
    ports:
      - ${PG_PORT}:5432
    hostname: ${HOST}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 80:80

  ingestion_script:
    build:
      context: ./
    env_file:
      - .env